apps/Backoffice/Frontend/Controllers/Courses/CoursesGetWebController.cs
using System;
using System.Threading.Tasks;
using CodelyTv.Mooc.CoursesCounters.Application.Find;
using CodelyTv.Shared.Domain.Bus.Query;
using Microsoft.AspNetCore.Mvc;

namespace CodelyTv.Apps.Backoffice.Frontend.Controllers.Courses
{
    [Route("Courses")]
    public class CoursesGetWebController : Controller
    {
        private const string VIEW = "Views/Courses/Index.cshtml";
        private readonly QueryBus _bus;

        public CoursesGetWebController(QueryBus bus)
        {
            _bus = bus;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var counterResponse =
                await _bus.Ask<CoursesCounterResponse>(new FindCoursesCounterQuery());

            ViewBag.Title = "Welcome";
            ViewBag.Description = "CodelyTV - Backoffice";
            ViewBag.CoursesCounter = counterResponse.Total;
            ViewBag.UUID = Guid.NewGuid().ToString();

            return View(VIEW);
        }
    }
}

apps/Backoffice/Frontend/Controllers/Courses/CoursesPostWebController.cs
using System.Threading.Tasks;
using CodelyTv.Mooc.Courses.Application.Create;
using CodelyTv.Shared.Domain.Bus.Command;
using Microsoft.AspNetCore.Mvc;

namespace CodelyTv.Apps.Backoffice.Frontend.Controllers.Courses
{
    [Route("Courses")]
    public class CoursesPostWebController : Controller
    {
        private const string VIEW = "Views/Courses/Index.cshtml";
        private readonly CommandBus _bus;

        public CoursesPostWebController(CommandBus bus)
        {
            _bus = bus;
        }

        [HttpPost]
        public async Task<IActionResult> Index(CoursesPostWebModel model, int coursesCounter)
        {
            if (ModelState.IsValid)
            {
                await _bus.Dispatch(new CreateCourseCommand(model.Id, model.Name, model.Duration));

                return RedirectToAction("Index", "CoursesGetWeb");
            }

            ViewBag.CoursesCounter = coursesCounter;
            ViewBag.UUID = model.Id;

            return View(VIEW);
        }
    }
}

apps/Backoffice/Frontend/Controllers/Home/HomeGetWebController.cs
using Microsoft.AspNetCore.Mvc;

namespace CodelyTv.Apps.Backoffice.Frontend.Controllers.Home
{
    public class HomeGetWebController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "Welcome";
            ViewBag.Description = "CodelyTV - Backoffice";
            return View("/Views/Home/Index.cshtml");
        }
    }
}

apps/Backoffice/Frontend/Views/Courses/Index.cshtml
@{
    ViewBag.TitlePage = "Courses";
}

<div class="max-w-sm rounded overflow-hidden shadow-lg float-left">
    <img class="w-full" src="https://codely.tv/pro/img/bg/cursos-codelytv-pro.png" alt="Sunset in the mountains">
    <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">Cursos</div>
        <p class="text-gray-700 text-base">
            Actualmente CodelyTV Pro cuenta con <b>@ViewBag.CoursesCounter</b> cursos.
        </p>
    </div>
</div>
@await Html.PartialAsync("/Views/Courses/NewCourseForm.cshtml")
<div class="clearfix mb-10"></div>
<hr class="mb-10">
@await Html.PartialAsync("/Views/Courses/ListCourses.cshtml")

apps/Backoffice/Frontend/Views/Courses/ListCourses.cshtml
<h3 class="font-sans text-gray-800 text-center text-3xl mb-10">Cursos existentes</h3>

<form action="" method="get" id="courses-filters" name="filter-courses">
    <div id="filter-rows">

    </div>
    <div class="clearfix"></div>
    <div class="mt-10 inline-block relative w-2/4">
        <button class="md:w-1/4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                id="add-field-button"
                onclick="addFilter(event)">
            Añadir filtro
        </button>

        <button class="md:w-1/4 bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                id="filter-button"
                onclick="filterCourses(event)">
            👉 Filtrar 👈
        </button>
    </div>
</form>

<table class="text-left w-full border-collapse">
    <thead>
    <tr>
        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Id</th>
        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Nombre</th>
        <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Duración</th>
    </tr>
    </thead>
    <tbody id="courses-list">

    </tbody>
</table>

<script>
    function addCoursesList(url) {
            const tableBody = document.getElementById("courses-list");
            fetch(encodeURI(url))
                .then(function (response) {
                    return response.json();
                })
                .then(function (courses) {
                    tableBody.innerHTML = "";
                    courses.forEach(function (course) {
                        let courseRow = document.createElement("tr");
                        courseRow.appendChild(tableCellFor(course.id));
                        courseRow.appendChild(tableCellFor(course.name));
                        courseRow.appendChild(tableCellFor(course.duration));
                        tableBody.appendChild(courseRow);
                    })
                });
        }
        function tableCellFor(text) {
            const cell = document.createElement("td");
            cell.appendChild(document.createTextNode(text));
            return cell;
        }
        function addFilter(e) {
            e.preventDefault();
            const filterRows = document.getElementById('filter-rows');
            const totalRows  = document.getElementById('filter-rows').childElementCount;
            const filterRowTemplate = "<div class=\"filter-row\">\n" +
                                      "    <div class=\"inline-block relative w-64 mr-3\">\n" +
                                      "        <label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"field\">\n" +
                                      "            Campo\n" +
                                      "        </label>\n" +
                                      "        <select name=\"filters[" +
                                      totalRows +
                                      "][field]\" id=\"field\"\n" +
                                      "                class=\"block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline\">\n" +
                                      "            <option value=\"id\">Identificador</option>\n" +
                                      "            <option value=\"name\">Nombre</option>\n" +
                                      "            <option value=\"duration\">Duración</option>\n" +
                                      "        </select>\n" +
                                      "        <div class=\"pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700\">\n" +
                                      "            <svg class=\"fill-current h-4 w-4\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\">\n" +
                                      "                <path d=\"M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z\"/>\n" +
                                      "            </svg>\n" +
                                      "        </div>\n" +
                                      "    </div>\n" +
                                      "    <div class=\"inline-block relative w-64 mr-3\">\n" +
                                      "        <label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"operator\">\n" +
                                      "            Operador\n" +
                                      "        </label>\n" +
                                      "        <select id=\"operator\" name=\"filters[" +
                                      totalRows +
                                      "][operator]\"\n" +
                                      "                class=\"block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline\">\n" +
                                      "            <option value=\"=\">es exactamente igual</option>\n" +
                                      "            <option value=\"CONTAINS\">contiene</option>\n" +
                                      "            <option value=\">\">es más grande que</option>\n" +
                                      "            <option value=\"<\">es más pequeño que</option>\n" +
                                      "        </select>\n" +
                                      "        <div class=\"pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700\">\n" +
                                      "            <svg class=\"fill-current h-4 w-4\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\">\n" +
                                      "                <path d=\"M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z\"/>\n" +
                                      "            </svg>\n" +
                                      "        </div>\n" +
                                      "    </div>\n" +
                                      "    <div class=\"inline-block relative w-64 mr-3\">\n" +
                                      "        <label class=\"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2\" for=\"value\">\n" +
                                      "            Valor\n" +
                                      "        </label>\n" +
                                      "        <input class=\"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500\"\n" +
                                      "               id=\"value\" type=\"text\" name=\"filters[" +
                                      totalRows +
                                      "][value]\" placeholder=\"Lo que sea...\">\n" +
                                      "    </div>\n" +
                                      "</div>";
            filterRows.insertAdjacentHTML('beforeend', filterRowTemplate);
        }
        function filterCourses(e) {
            e.preventDefault();
            const form = document.forms["filter-courses"];
            const inputs = Array.from(form.getElementsByTagName("input"))
                                .concat(Array.from(form.getElementsByTagName("select")));
            const urlParts = inputs.map(input => input.name + "=" + input.value);
            const url = "http://localhost:8092/courses" + urlParts.join("&");
            addCoursesList(url);
        }
</script>
<script>
    addCoursesList("http://localhost:8092/courses");
</script>

apps/Backoffice/Frontend/Views/Courses/NewCourseForm.cshtml
@using CodelyTv.Apps.Backoffice.Frontend.Extension.Validators
@model CoursesPostWebModel

<form class="w-full max-w-lg float-right" method="post" action="@Url.Action("Index", "CoursesPostWeb")">
    <h2 class="block uppercase tracking-wide text-gray-700 text-3xl font-bold mb-2">Crear curso</h2>
    <div class="flex flex-wrap mb-6 -mx-3">
        <div class="w-full md:w-full px-3 mb-6 md:mb-0">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                Identificador
            </label>
            <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                   id="grid-first-name" asp-for="Id" name="id" type="text" placeholder="En formato UUID" value="@ViewBag.UUID">
            @Html.ValidationSummaryByProperty(ViewData.ModelState, "Id", "text-red-500 text-xs italic")

        </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                Nombre
            </label>
            <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                   id="grid-first-name" asp-for="Name" name="name" type="text" placeholder="DDD en PHP">
            @Html.ValidationSummaryByProperty(ViewData.ModelState, "Name", "text-red-500 text-xs italic")

        </div>
        <div class="w-full md:w-1/2 px-3">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
                Duración (en inglés)
            </label>
            <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                   id="grid-last-name" asp-for="Duration" name="duration" type="text" placeholder="8 days">
            @Html.ValidationSummaryByProperty(ViewData.ModelState, "Duration", "text-red-500 text-xs italic")
        </div>
    </div>
    @Html.Hidden("CoursesCounter", ViewBag.CoursesCounter, null)
    <div class="flex flex-wrap mb-6">
        <button class="md:w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                type="submit">
            Crear curso!
        </button>
    </div>
</form>

apps/Backoffice/Frontend/Views/Home/Index.cshtml
@{
    ViewBag.TitlePage = "Home";
}

Estamos en la home!

apps/Backoffice/Frontend/Views/Shared/_Footer.cshtml
<footer class="flex items-center justify-between flex-wrap bg-teal-900 p-5 mt-10">
    <div class="container mx-auto px-4">
        <p class="text-teal-200">
            🤙 CodelyTV - El mejor backoffice de la historia
        </p>
    </div>
</footer>

apps/Backoffice/Frontend/Views/Shared/_Header.cshtml
<header>
    <nav class="flex items-center justify-between flex-wrap bg-teal-900 p-5">
        <div class="flex items-center flex-shrink-0 text-white mr-6">
            <a href="@Url.Action("Index", "HomeGetWeb")">
                <img src="images/logo.png" alt="" width="150px">
            </a>
        </div>
        <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
            <div class="text-sm lg:flex-grow">
                <a href="#"
                   class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
                    Usuarios
                </a>
                <a href="@Url.Action("Index", "CoursesGetWeb")"
                   class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
                    Cursos
                </a>
                <a href="#" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white">
                    Vídeos
                </a>
            </div>
            <div>
                <a href="#"
                   class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">
                    Entrar
                </a>
            </div>
        </div>
    </nav>
</header>

apps/Backoffice/Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>@ViewData["Title"]</title>
    <meta name="description" content="@ViewData["Description"]"/>
    <link href="https://unpkg.com/tailwindcss@@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
@await Html.PartialAsync("_Header")
<div class="container mx-auto px-4 p-5">
    <h1 class="font-sans text-gray-800 text-center text-5xl mb-10">@ViewData["TitlePage"]</h1>
    @RenderBody()
</div>
<div class="clearfix"></div>
@await Html.PartialAsync("_Footer")
</body>
</html>